name: Release CI
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Mark as Pre-release'
        required: false
        type: boolean
      publish:
        description: 'Publish release'
        required: false
        type: boolean
        default: true
jobs:
  job_armv8:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g
        
      - name: Add Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleArmv8Release

      - name: Determine the latest Build Tools version installed
        shell: bash
        run: echo "BUILD_TOOL_VERSION=$(ls "$ANDROID_HOME/build-tools/" | tail -n 1)" >> $GITHUB_ENV
        
      - name: Sign APK
        id: sign_app
        uses: SnapEnhance/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/armv8/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapenhance-armv8-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
  job_armv7:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Add Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleArmv7Release

      - name: Determine the latest Build Tools version installed
        shell: bash
        run: echo "BUILD_TOOL_VERSION=$(ls "$ANDROID_HOME/build-tools/" | tail -n 1)" >> $GITHUB_ENV

      - name: Sign APK
        id: sign_app
        uses: SnapEnhance/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/armv7/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapenhance-armv7-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  job_universal:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g
        
      - name: Add Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleAllRelease

      - name: Determine the latest Build Tools version installed
        shell: bash
        run: echo "BUILD_TOOL_VERSION=$(ls "$ANDROID_HOME/build-tools/" | tail -n 1)" >> $GITHUB_ENV

      - name: Sign APK
        id: sign_app
        uses: SnapEnhance/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/all/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload universal
        uses: actions/upload-artifact@v4
        with:
          name: snapenhance-universal-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  job_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew manager:assembleRelease

      - name: Determine the latest Build Tools version installed
        shell: bash
        run: echo "BUILD_TOOL_VERSION=$(ls "$ANDROID_HOME/build-tools/" | tail -n 1)" >> $GITHUB_ENV

      - name: Sign APK
        id: sign_app
        uses: SnapEnhance/sign-android-release@master
        with:
          releaseDirectory: manager/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: manager
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  job_release:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish == true }}
    needs: [job_armv8, job_armv7, job_universal, job_manager]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get current build version
        id: version-env
        run: |
          ./gradlew getVersion
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: bins/
          merge-multiple: true

      - name: Publish APK
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.prerelease }}
          files: bins/*.apk
          tag_name: v${{ env.version }}
